server.port=8081
module1.service.url=${MODULE1_SERVICE_URL:http://localhost:8080}

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
cache.stats.print.interval=60000
